model:
  class_path: src.training.modules.FinetuningModuleDenseHead
  init_args:
    model:
      class_path: src.ribonanzanet.RibonanzaNet
    out_size: 2
    pooling:
      type: 'mean'
      dim: -2
    ckpt_dir: ${RN_COV_CKPT}

trainer:
  precision: 16-mixed
  accelerator: gpu

optimizer:
  class_path: torch.optim.AdamW

lr_scheduler:
  class_path: src.training.optimisation.lr_schedulers.LinearWarmupAndInverseSqrtDecayLR

data:
  class_path: src.data.datamodules.XarrayDataModule
  init_args:
    target_variables:
      - [[2A3, DMS], target]
    input_variables:
      - [[sequence], x]
